name: recreate-dependabot-prs

on:
  workflow_call:
    secrets:
      GITHUB_API_TOKEN:
        description: A GitHub token to use for the API calls. This cannot be the default GITHUB_TOKEN as Dependabot requires the user to have push permissions
        required: true
    inputs:
      operating-system:
        description: The operating system to use (default `ubuntu-latest`)
        required: false
        default: ubuntu-latest
        type: string
      repo:
        description: The repo-owner/repo string for the repository filter
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: create-comment
    runs-on: ${{ inputs.operating-system}}
    if: github.repository == inputs.repo
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on PRs
        run: |
          DEPENDABOT_PRS=$(
              gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/${{ inputs.repo }}/pulls?state=open" \
                  | jq -r '.[] | select(.user.login == "dependabot[bot]")' \
                  | jq -r .issue_url
              )
          printf "Found the following PR issue urls: \n${DEPENDABOT_PRS} \n"
          for PR in ${DEPENDABOT_PRS}; do
              PARSED_URL=$(echo ${PR} | sed 's/api\.//' | sed 's/repos\///' | sed 's/issues/pull/')
              gh pr comment -b "@dependabot recreate" "${PARSED_URL}"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.COMMENT_TOKEN }}
