name: label-sync

on:
  workflow_call:
    inputs:
      operating-system:
        description: The operating system to use (default `ubuntu-latest`)
        required: false
        default: ubuntu-latest
        type: string
      with-submodules:
        description: Whether to include submodules when checking out the repository (default `false`)
        required: false
        default: 'false'
        type: string
      merge-labels:
        description: Whether to merge labels or not
        required: false
        default: false
        type: boolean
      repository-overwrite-labels:
        description: The repository to get overwrite labels from. Only used if merge-labels is true!
        required: false
        type: string

jobs:
  label-sync:
    name: Label sync
    runs-on: ${{ inputs.operating-system }}
    steps:
      - name: Checkout Core labels
        uses: actions/checkout@v4
        with:
          path: core-labels
          sparse-checkout: .github/labels.yml
          sparse-checkout-cone-mode: false
          repository: sapphiredev/.github
          submodules: ${{ inputs.with-submodules }}
      - name: Checkout Overwrite Labels
        if: ${{ inputs.merge-labels == true }}
        uses: actions/checkout@v4
        with:
          path: overwrite-labels
          sparse-checkout: .github/labels.yml
          sparse-checkout-cone-mode: false
          repository: ${{ inputs.repository-overwrite-labels }}
          submodules: ${{ inputs.with-submodules }}
      - name: Merge labels
        if: ${{ inputs.merge-labels == true }}
        run: |
          yq '. *+ load("core-labels/.github/labels.yml")' overwrite-labels/.github/labels.yml > labels.yml
      - name: Move core labels
        if: ${{ inputs.merge-labels == false }}
        run: mv core-labels/.github/labels.yml labels.yml
      - name: Run Label Sync
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: labels.yml
